// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVc18-dyrHsQBfvaaN2cerbrVEAXtACg',
    appId: '1:334566462594:web:eb2cb2946e5169d18b509b',
    messagingSenderId: '334566462594',
    projectId: 'flowplan-ai-a9bfe',
    authDomain: 'flowplan-ai-a9bfe.firebaseapp.com',
    storageBucket: 'flowplan-ai-a9bfe.firebasestorage.app',
    measurementId: 'G-LBZFP88D53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOdaz1b5zQ3oXYFtVaaXXEyYu6r_WzhQ',
    appId: '1:334566462594:android:c160bc72afd1142b8b509b',
    messagingSenderId: '334566462594',
    projectId: 'flowplan-ai-a9bfe',
    storageBucket: 'flowplan-ai-a9bfe.firebasestorage.app',
  );
}
